# Generated by Django 2.1.5 on 2019-01-10 20:18

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], max_length=256)),
                ('opt_out', models.BooleanField(blank=True)),
                ('hard_bounce', models.BooleanField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=256)),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('drivers_license_number', models.CharField(blank=True, max_length=8)),
                ('birthdate', models.DateField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_app.ProductPackage')),
            ],
        ),
    ]
