# Generated by Django 2.1.5 on 2019-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general question', 'General Question'), ('data', 'Data'), ('feedback', 'Issues/Feedback'), ('technical question', 'Technical Question'), ('product', 'Product Questions')], default='--select--', max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
